### ISSUE TITLE
fatal error: algorithm

### ISSUE THREAD

**Issue by Sod-Almighty** [107-systems/107-Arduino-Debug#11]
```
fatal error: algorithm: No such file or directory
 #include <algorithm>
          ^~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Nano.
```
I do wish people would test their code before submitting it to the Arduino repo.

**Comment by aentinger** [comment]
Thank you very much for your report. This error is caused because `algorithm` is a part of the C++ standard library which does not exist for AVR boards such as the Arduino Nano. #12 fixes the `library.properties` file in such a way that it won't be signalled as available for AVR anymore, therefore sparing others the frustration you've must have experienced.
